In [8]:
import theano
import numpy as np
table = np.eye(3)
index = [1,2]
table[index]
np.zeros([2,3],dtype="int32")

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
import numpy as np
A=np.zeros(2)
B=np.zeros((2,2))
print A + B[:,0]
print A + B[0,:]

[ 0.  0.]
[ 0.  0.]


In [35]:
import numpy as np
from collections import OrderedDict
A= dict()
A["test"] = 1
#print **A
#A=np.array([1,2])
np.savez("test.npz",**A)
C=np.load("test.npz")
A=np.array([1,2])
for kk, pp in C.iteritems():
    print kk,pp

test 1


In [39]:
import numpy as np
print np.eye(3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
