In [1]:
import theano

import theano.tensor as T

A = T.ivector("A")

B = T.imatrix("B")

In [2]:
C = A[B]
A_in = [1,2,3]
B_in = [[0,1],[1,2]]
func = theano.function([A,B],C)
func(A_in,B_in)

array([[1, 2],
       [2, 3]])

In [3]:
D_out=func(A_in,B_in)
len(D_out)

2

In [6]:
A = T.imatrix("A")
B = T.imatrix("B")
C = A[B]
A_in = [[1,2],[2,3],[3,4]]
B_in = [[0,1],[1,2]]
func = theano.function([A,B],C)
func(A_in,B_in)

array([[[1, 2],
        [2, 3]],

       [[2, 3],
        [3, 4]]])

In [6]:
import theano
import theano.tensor as T
B=T.imatrix("B")

A=T.imatrix("A")

C=A*B

func1 = theano.function(inputs=[A,B],outputs=C)

D=T.dscalar("D")

E=T.imatrix("E")

F = D * E

func2 = theano.function(inputs=[E,D],outputs=F)
print func1([[1,2,3]],[[2,3,4]])
print func2([[1,2]],4)



[[ 2  6 12]]
[[ 4.  8.]]


In [8]:
import theano
import theano.tensor as T
B=T.itensor3("B")
C = B.sum(0)
func1 = theano.function(inputs=[B],outputs=C)
print func1([[[1,2,3],[2,3,4]]])
A= [[1,2,3],[2,3,4]]

#print A[0][2]

[[1 2 3]
 [2 3 4]]


In [18]:
import theano
import theano.tensor as T
import numpy as np 
B=T.imatrix("B")
C = T.shape(B)
#C = T.sum(B,0)
func1 = theano.function(inputs=[B],outputs=C)
print func1([[1,2,3],[2,3,4]])
np.shape([[1,2,3],[2,3,4]])

[2 3]


(2, 3)

In [23]:
import theano
import theano.tensor as T
import numpy as np 
B=T.imatrix("B")
A=theano.tensor.identity_like(np.eye(3))
C=A[B]
print type(A)
func1 = theano.function(inputs=[B],outputs=C,on_unused_input='ignore')
func1([[2,2],[2,2]])

<class 'theano.tensor.var.TensorVariable'>


array([[[ 0.,  0.,  1.],
        [ 0.,  0.,  1.]],

       [[ 0.,  0.,  1.],
        [ 0.,  0.,  1.]]])

In [45]:
import theano
import theano.tensor as T
import numpy as np 
B=T.imatrix("B")
A=T.imatrix("A")
D=T.extra_ops.compress(A>0,A)
C = B.repeat(5,axis=1)
func1 = theano.function(inputs=[B],outputs=C,on_unused_input='ignore')
func2 = theano.function(inputs=[A],outputs=D,on_unused_input='ignore')
func2([[0,0,1,2],[1,2,3,1]])
#print (func1([[1,2]]))
#T.extra_ops.compress(A>0,A)

array([1, 2, 1, 2, 3, 1])

In [49]:
import theano
import theano.tensor as T
import numpy as np 
B=T.imatrix("B")
A= T.neq(B,1)
func1 = theano.function(inputs=[B],outputs=A,on_unused_input='ignore')
print func1(np.eye(3,dtype="int32"))

[[0 1 1]
 [1 0 1]
 [1 1 0]]
